name: pawon
description: A clean and focused recipe app.

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animate_do: ^2.0.0
  cloud_firestore: ^2.5.2
  cupertino_icons: ^1.0.2
  device_preview: ^0.7.4
  dotted_border: ^2.0.0+1
  equatable: ^2.0.3
  firebase: ^9.0.1
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_hex_color: ^2.0.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.1.0
  ionicons: ^0.1.2
  page_transition: ^2.0.2
  simple_animations: ^3.1.1
  supercharged: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.3
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/launcher_icon.png"
  adaptive_icon_background: "#f7f7f7"
  adaptive_icon_foreground: "assets/launcher_icon.png"

flutter_native_splash:
  android: true
  ios: true
  color: "#f7f7f7"
  image: "assets/launcher_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
  